Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChrisConnorBlogAssessment.Models;

namespace ChrisConnorBlogAssessment.Controllers
{
    [Authorize(Roles = "Theatre_Administrator,Theatre_Staff")]
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Blog).Include(c => c.User);
            return View(comments.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        //public ActionResult Create()
        //{
        //    ViewBag.BlogId = new SelectList(db.Blogs, "BlogId", "Title");
        //    ViewBag.Id = new SelectList(db.Users, "Id", "Forename");
        //    return View();
        //}

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CommentId,Content,DateAdded,BlogId,Id")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BlogId = new SelectList(db.Blogs, "BlogId", "Title", comment.BlogId);
            ViewBag.Id = new SelectList(db.Users, "Id", "Forename", comment.Id);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.BlogId = new SelectList(db.Blogs, "BlogId", "Title", comment.BlogId);
            ViewBag.Id = new SelectList(db.Users, "Id", "Forename", comment.Id);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommentId,Content,DateAdded,BlogId,Id")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BlogId = new SelectList(db.Blogs, "BlogId", "Title", comment.BlogId);
            ViewBag.Id = new SelectList(db.Users, "Id", "Forename", comment.Id);
            return View(comment);
        }

        // GET: Comments/Delete/5
        [Authorize(Roles = "Theatre_Administrator,Theatre_Staff")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [Authorize(Roles = "Theatre_Administrator,Theatre_Staff")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChrisConnorBlogAssessment.Models;
using ChrisConnorBlogAssessment.ViewModels;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ChrisConnorBlogAssessment.Controllers
{
    [Authorize(Roles = "Theatre_Administrator")]
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Users
        public ActionResult Index(string category)
        {

            var roleStore = new RoleStore<IdentityRole>(db);
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var userStore = new UserStore<ApplicationUser>(db);

            RolesAndUsersViewModel model = new RolesAndUsersViewModel();
            
            model.Roles = roleManager.Roles.ToList();
            model.Users = new List<UserAndRolesViewModel>();

            foreach (var u in userManager.Users.ToList())
            {
                
                var temp = new UserAndRolesViewModel
                {
                    UserId = u.Id,
                    UserName = u.UserName,
                    FullName = u.Forename + " " + u.Surname,
                    Email = u.Email,
                    IsActive = !u.LockoutEnabled,
                    Roles = new List<RoleViewModel>()
                };

                foreach (var r in roleManager.Roles.ToList())
                {
                    if (userManager.IsInRole(u.Id, r.Name))
                    {
                        temp.Roles.Add(new RoleViewModel
                        {
                            RoleId = r.Id,
                            RoleName = r.Name
                        });
                    }
                }

                model.Users.Add(temp);
            }
           
            return View(model);
        }
        public ActionResult PromoteUser(string email)
        {
            var roleStore = new RoleStore<IdentityRole>(db);
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var userStore = new UserStore<ApplicationUser>(db);

            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            email.Replace("-", "@");

            var user = userManager.FindByEmail(email);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var promoteResult = userManager.AddToRole(user.Id, RoleNames.RoleStaff);
            var demoteResult = userManager.RemoveFromRole(user.Id, RoleNames.RoleUser);

            return RedirectToAction("Index");
            //return View();
        }

        public ActionResult DemoteUser(string email)
        {
            var roleStore = new RoleStore<IdentityRole>(db);
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var userStore = new UserStore<ApplicationUser>(db);

            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = userManager.FindByEmail(email);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (userManager.IsInRole(user.Id, RoleNames.RoleStaff))
            {
                var demoteResult = userManager.RemoveFromRole(user.Id, RoleNames.RoleStaff);
                var userresult = userManager.AddToRole(user.Id, RoleNames.RoleUser);
            }

            return RedirectToAction("Index");
            //return View();
        }

        public ActionResult ToggleState(string email)
        {
            var roleStore = new RoleStore<IdentityRole>(db);
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var userStore = new UserStore<ApplicationUser>(db);

            if (email == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            email.Replace("-", "@");

            var user = userManager.FindByEmail(email);
            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (!userManager.IsLockedOut(user.Id))
            {
                
                userManager.SetLockoutEnabled(user.Id, true);
                userManager.SetLockoutEndDate(user.Id, DateTime.Now.AddYears(5));
                user.IsActive = false;
            }
            else
            {
                userManager.SetLockoutEnabled(user.Id, false);
                userManager.SetLockoutEndDate(user.Id, DateTime.Now.AddDays(-1));
                user.IsActive = true;
            }
            //user.LockoutEnabled = !user.LockoutEnabled;

            return RedirectToAction("Index");
            //return View();
        }
    }

}

Views/Shared/_Layout.cshtml
@using ChrisConnorBlogAssessment.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cumbernauld Theatre Group | Local Theatre Group, Cumbernauld, Glasgow</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
        body {
            padding-top: 65px;    
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                @*@Html.ActionLink("Local Theatre Group", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <a href="/" class="navbar-brand"><span class="icon-theatre-group"></span> Local Theatre</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Blogs", "BlogsAndCategories", "Blogs")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (User.IsInRole(RoleNames.RoleAdministrator) || User.IsInRole(RoleNames.RoleStaff))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administration<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Manage Blogs", "Index", "Blogs")</li>
                                <li>@Html.ActionLink("Manage Users", "Index", "Users")</li>
                                <li>@Html.ActionLink("Manage Categories", "Index", "Categories")</li>
                                <li>@Html.ActionLink("Manage Comments", "Index", "Comments")</li>
                            </ul>
                        </li>
                        

                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - Cumbernauld Theatre Group</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>